lib/update-shrinkwrap.js

Fixes issue https://github.com/greenkeeperio/greenkeeper-shrinkwrap/issues/12.
Problem: NodeJS's latest LTS Version (v6.10.3) includes npm 3.10.10. This version of npm doesn't lock down devDependencies in the shrinkwrap file by default:
> Starting with npm v4.0.1, devDependencies are included when you run npm shrinkwrap and follow the usual rules as to when they're installed.
https://docs.npmjs.com/cli/shrinkwrap#other-notes
Right now, if a devDependency is updated by greenkeeper, greenkeeper tries to update the shrinkwrap as well. However, because the devDependencies are not locked down in the shrinkwrap, there are no changes. Therefore the git commit fails, because git doesn't allow empty commits by default. Which causes the Travis build to break. Which results in greenkeeper filing an …

fix: shrinkwrap commit fails if on dev dependency update

---

.travis.yml
README.md
package.json

This removes `npm5` instructions from the docs since it is out of beta and now available as `npm@5`. It also updates our setup to use `npm`.
The `npm5` cli tool will still work though. I didn't remove support for it, since it is still maintained and used.

chore: npm 5 is out of beta

---

ci-services/circleci.js

Hey,
I think we could detect the first push on Circle CI with `!env.CIRCLE_PREVIOUS_BUILD_NUM`. I haven't tested this on Circle CI yet, though.
If it works, we wouldn't need the git tricks in #27
@ethanrubio Could you have a look at this?
Best,
Finn

fix(circleci): use CIRCLE_PREVIOUS_BUILD_NUM to detect the first push

---

lib/update-lockfile.js

Since yarn doesn't accept -S when installing regular dependencies
#40 closes
I didn't see it before but this seems to be a duplicate of #34  so whichever implementation is prefered

Fix installing regular dependencies using yarn

---

lib/update-lockfile.js
package-lock.json
update.js

This passes a new option: `npm: boolean` to `updateLockfile` to allow both `yarn.lock` and `package-json.lock` to be updated.
Sadly there is no test suite (yet) to add tests for this.  
I strongly vote for having at least unit tests.

feat: allow package-json.lock and yarn.lock to be uppdated simultaneously, fixes #39

---

lib/update-lockfile.js

Fix error: SyntaxError: Identifier 'flag' has already been declared
Fixes #49

fix: Use strict mode to fix syntax error on Node 4

---

update.js

While `fs#exists` is deprecated, `fs#existsSync` is not. This uses `existsSync` instead of `readFileSync` with try-catch to determine which lock files exist.

refactor: Use fs#existsSync instead of fs#readFileSync

---

update.js

Lately, **all** Greenkeeper builds of our projects using `npm-shrinkwrap.json` have been failing due to a regression in `update.js`, because neither the `yarn install` or `npm install` step is executed, resulting in this script to try to commit nothing:
```
$ greenkeeper-lockfile-update
child_process.js:524
throw err;
^
Error: Command failed: git commit -m "chore(package): update lockfile
https://npm.im/greenkeeper-lockfile"
at checkExecSyncError (child_process.js:481:13)
at execSync (child_process.js:521:13)
at updateLockfile (/home/travis/.nvm/versions/node/v6.11.1/lib/node_modules/greenkeeper-lockfile/lib/update-lockfile.js:63:3)
at Module.update [as exports] (/home/travis/.nvm/versions/node/v6.11.1/lib/node_modules/greenkeeper-lockfile/update.js:60:3)
at Object.<anonymous> …
```

Fix completely broken shrinkwrap support

---

ci-services/circleci.js
ci-services/index.js
ci-services/jenkins.js
ci-services/tests.js
ci-services/travis.js
ci-services/wercker.js
lib/config.js
lib/extract-dependency.js
lib/git-helpers.js

Right now, only a few files have the `'use strict'` directive. I am not entirely sure why this isn't resulting in error like the following:
```
λ node --version
v4.0.0
λ echo let a = 1 > test-node4.js
λ node test-node4.js
E:\Projects\experiments\test-node4.js:1
(function (exports, require, module, __filename, __dirname) { let a = 1
^^^
SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
at exports.runInThisContext (vm.js:53:16)
at Module._compile (module.js:413:25)
at Object.Module._extensions..js (module.js:452:10)
at Module.load (module.js:355:32)
at Function.Module._load (module.js:310:12)
at Function.Module.runMain (module.js:475:10)
at startup (node.js:117:18)
at node.js:951:3
``` 
This enables strict mode in all js files.

fix: Enable strict mode in all files

---

ci-services/circleci.js
ci-services/travis.js

Use environment variable `BUILD_LEADER_ID`, if set, to determine the build leader. Allow to run `greenkeeper-lockfile-upload` on a specific Node version or Travis stage.
Similar to [travis-deploy-once/index.js#L49](https://github.com/semantic-release/travis-deploy-once/blob/9dadfd157e6b01ca48fe71a885d091fcb341431c/index.js#L49)

feat: allow to configure build leader id via env variable

---

README.md

This PR adds documentation on how to use this with workflows in CircleCI. `greenkeeper-lockfile` must be run in the first job in the workflow. To ensure the job that runs `greenkeeper-lockfile` is always first, all other jobs must wait for it to finish before running.
See issue #50

docs(README): document how to use with CircleCI workflows

---

.gitignore
README.md
lib/update-lockfile.js
package-lock.json
package.json
test/lib/update-lockfile.js

This PR implements the functionality discussed in #66. For the sake of not breaking things I added tests for the lockfile creation. I tried to replicate the testing framework used for https://github.com/greenkeeperio/greenkeeper, however I'm using sinon to stub and spy all the `exec` calls. I'll happily replace that with another solution that you prefer. Looking forward to getting some feedback on this :)

Add yarn args from environment variable

---

ci-services/codeship.js
ci-services/tests.js
upload.js

Implements support for Codeship Pro, updates lockfile on commit messages matching `/^(chore|fix)\(package\): update [^ ]+ to version.*$/mi`
https://github.com/greenkeeperio/greenkeeper-lockfile/issues/25

Codeship CI Integration

---

README.md

Instead of just mentioning that `npm install -g npm@latest` should be skipped, let's show folks how they can do that.
This example has been tested and verified here: https://github.com/sywac/sywac/blob/51fe43e74740d29e9ad7c87aa593c16ee07307b2/.travis.yml#L8

docs: show how to skip npm latest in travis example

---

lib/update-lockfile.js
test/lib/update-lockfile.js

Currently, the lockfile commit for a dependency that is declared with a caret (`^`) in `package.json` writes an exact version into `yarn.lock`.
This means that when checking out the branch and running `yarn` to install the dependencies, `yarn.lock` will be modified again, leaving the repo in an unclean state:
```
-"@types/karma@1.7.0":
+"@types/karma@^1.7.0":
```
This PR fixes that by specifying the dependency's version range instead of the `--exact` / `--tilde` switches when installing via yarn.
I've tested it on one of my repos with exact, tilde and caret ranges and the lockfile commit always used the correct prefix, resulting in a stable lockfile state.
Please do tell me if I`m missing something that makes using the switches necessary, they seemed like an overly complex way of …

fix(yarn): preserve caret ranges

---

ci-services/tests.js

Comparing to an empty string doesn't work because the env var will be undefined on other CI systems and therefore return true.

fix(ci-test): fix env test for bitrise

---

ci-services/jenkins.js

Seems like #73 has gone stale. This uses the environment variable.

fix: Use build number from env on Jenkins

---

ci-services/teamcity.js
ci-services/tests.js
lib/git-helpers.js

This PR adds support for Team City. 
Team City has all the build related information in certain configuration parameters, but in order to make them available to `greenkeeper-lockfile`, they need to be manually mapped to environment variables in the build configuration.
This PR assumes that these two variables are available to the script:
* `VCS_ROOT_URL` which is mapped to the `vcsroot.<vcsrootid>.url` parameter
* `VCS_ROOT_BRANCH` which is mapped to the `teamcity.build.branch` parameter
The `GH_TOKEN` environment variable also needs to be defined, but that needs to happen independently of the CI server.
In order to detect if builds are coming from a PR or not, we can check the name of the branch. If it ends with `/merge` or `/head`, it means it is  a pull request according to this …

feat: add team city support

---

ci-services/tests.js

Bitrise now sets `BITRISE_IO = true` to indicate the build is running on bitrise.io. This variable is not set by the Bitrise CLI. Other CI services, such as [CircleCI](https://circleci.com/docs/2.0/env-vars/#general-environment-variables), also set `CI = true`, which makes the `CI` enviornment variable unreliable.  `BITRISE_BUILD_NUMBER` is the build number on bitrise.io and should no longer be necessary.
https://devcenter.bitrise.io/faq/available-environment-variables/
More information here: https://github.com/bitrise-io/bitrise/issues/591

Bitrise now sets BITRISE_IO

---

ci-services/jenkins.js

This is a refresh of the now stale #73 - includes those changes but with code review comments addressed, as well as addressing the differing branch name formats for different Jenkins plugins as brought up in #145

Jenkins improvements

---

ci-services/drone.js
ci-services/tests.js

Adds support for [Drone.io](https://drone.io) which has a hosted solution as well as a service implementation.
cc: @bradrydzewski who is the lead on Drone

Add Drone.io support

---

lib/git-helpers.js
lib/update-lockfile.js
test/lib/update-lockfile.js
test/update.js
update.js

This fixes the tests, and implements the missing functionality required to make monorepo support work. See https://travis-ci.org/oe/gk-lockfile-test-monorepo/jobs/382719531 for a working build log.

fix: fix monorepo support

---

update.js

moved the `!info.branchName` test to the top & added a test for the initial branch

fix: bail on greenkeeper initial branches

---

README.md
ci-services/circleci.js

This adds support to use greenkeeper-lockfile in CircleCI workflows.
Successful builds: https://circleci.com/gh/patkub/test-greenkeeper-lockfile-circleci-first-push/tree/greenkeeper%2Ftest-greenkeeper-lockfile-appveyor-package-1.0.73
On the initial greenkeeper commit, the lockfile gets [updated](https://circleci.com/gh/patkub/test-greenkeeper-lockfile-circleci-first-push/188) and [uploaded](https://circleci.com/gh/patkub/test-greenkeeper-lockfile-circleci-first-push/190). On the "chore(package): update lockfiles" commit [update](https://circleci.com/gh/patkub/test-greenkeeper-lockfile-circleci-first-push/191) and [upload](https://circleci.com/gh/patkub/test-greenkeeper-lockfile-circleci-first-push/193) succeed.
Workflow support for 1.0.0 (with firstPush) is implemented in …

feat: circleci workflow support for 2.0.0 (monorepos)

---

ci-services/teamcity.js

Update lockfile now commits with "lockfile" or "lockfiles" depending on how many files are changed.
https://github.com/greenkeeperio/greenkeeper-lockfile/blob/master/lib/update-lockfile.js#L66-L73
#164

fix: team city update lockfile(s) plural commit message regex

---

upload.js

fixes #174 
as mentioned [in the issue thread](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/174#issuecomment-401680470), i used the [suggestion](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/174#issuecomment-400363829) from @richardson-trevor and verified that it worked properly in [this PR](https://github.com/travi/scaffolder-sub-command/pull/72)
this PR is not enough to get the amend feature working, but does fix the inability to force push after amending. i think it comes down to your call whether this should be merged before fixing the resulting looping of builds mentioned [in the issue thread](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/174#issuecomment-401680470)

fix: compare lease against proper remote

---

upload.js

hasLockFileCommit needs to be calles after gk-origin remote url is configured.

fix(upload): rearrange hasLockFileCommit

---

lib/git-helpers.js
test/__snapshots__/update.js.snap

There is more context in https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164#issuecomment-405308480
When configuring the remote to use `GH_TOKEN` in `upload.js` it is only done for the `gk-origin` remote, but then in `git-helpers#hasLockfileCommit` a `git fetch` is done, which can fail if there is a `origin` remote defined, as this one is not configured with `GH_TOKEN`.
This PR updates `hasLockfileCommit` to make the fetch from `gk-origin`.

fix(hasLockfileCommit): specify origin when fetching

---

ci-services/gitlab.js
ci-services/tests.js

This allows the usage of Greenkeeper.io with GitLab CI/CD for GitHub (https://about.gitlab.com/solutions/github/).

feat: Add GitLab-CI

---

ci-services/gitlab.js
lib/git-helpers.js

Fix a misunderstanding because Greenkeeper and GitLab define a "slug" differently.

fix: repoSlug for GitLab CI
