greenkeeperio/greenkeeper-lockfile

- README.md
- ci-services/index.js
- ci-services/tests.js
- ci-services/travis.js
- update.js
- upload.js
> feat: add support for adding more CI services

- README.md
I didn't understand what this project did until I read the last section. Maybe it should come first? I think this would have helped me.
> Open readme with a summary of what it does

- README.md
- ci-services/circleci.js
- ci-services/tests.js
- ci-services/travis.js
- lib/git-helpers.js
- lib/update-lockfile.js
- update.js
This PR is based on the great work by @ethanrubio in #18.
It adds a little cleanup, based on _my_ mess 🙈 and additions to the README.md
@ethanrubio I just gave you commit bits to this repo. I don't want to merge this without you having another look at my changes. Please add your review and merge the PR if you like it. A new version will become available on npm as soon as the master build passes.
Closes #18
> Add Circle CI

- lib/update-lockfile.js
This should address #22.
Closes #22
> fix(yarn): correctly preserve prefix

- update.js
- upload.js
> Invoke strict mode in scripts

- update.js
- upload.js
This should generically address https://github.com/greenkeeperio/greenkeeper-lockfile/issues/30 and any similar issues.
If it's not very obviously a greenkeeper branch (because of no env var), then just return early.
> Check that info.branchName exists before working with it

- .travis.yml
Node 8 is the stable version and out already for quite some while, let's test on that as well :)
> chore(travis): run tests on Node 8

- README.md
> fix Readme instructions for node 9

- lib/update-lockfile.js
The original PR is always created via the user: greenkeeperio-bot
> Align git username

- ci-services/semaphoreci.js
- ci-services/tests.js
Tested and works with the setup command
```
npm i -g cbothner/greenkeeper-lockfile
```
Fixes #96
> Add Semaphore as a service

- lib/update-lockfile.js
Using env vars: GK_LOCK_COMMIT_EMAIL and GK_LOCK_COMMIT_NAME
Fixes #122
> Allow configuring commit email and name

- upload.js
rebased version of https://github.com/greenkeeperio/greenkeeper-lockfile/pull/86#pullrequestreview-109373719
> Adds fallback when gk-origin remote exists

- README.md
- lib/git-helpers.js
> feat: default branch is configurable

- ci-services/jenkins.js
Consult env vars in order: `CHANGE_TARGET`, `CHANGE_BRANCH`, `BRANCH_NAME`, `GIT_BRANCH` to resolve original branch.
> Fix Jenkins Multibranch pipeline jobs

- test/__snapshots__/update.js.snap
- test/lib/__snapshots__/update-lockfile.js.snap
- test/lib/update-lockfile.js
- test/update.js
Hey,
I tried to change something in this module, but immediately all of the tests were failing. The main problem was that `exec.getCall(x)` is used a lot, which needs to be updated everywhere when something is added.
To make it easier to change things in the module, but still have strict testing I changed one of the tests to using jest snapshot testing. This way tests can be easily updated with `npm test -- -u` but it's also easy to review changes.
Additionally I refactored the test a bit, but that's not necessary for adapting the snapshot tests 😉 
Best,
Finn
> use snapshot tests

- README.md
- ci-services/appveyor.js
- ci-services/tests.js
- lib/update-lockfile.js
- test/lib/__snapshots__/update-lockfile.js.snap
- test/lib/update-lockfile.js
- update.js
@patkub I did the rebase! 
closes https://github.com/greenkeeperio/greenkeeper-lockfile/pull/142
> AppVeyor CI

- ci-services/codebuild.js
- ci-services/tests.js
- lib/git-helpers.js
@coderbyheart rebased & adapted to [greenkeeper-lockfile v2](https://github.com/greenkeeperio/greenkeeper-lockfile/issues/164)!
closes https://github.com/greenkeeperio/greenkeeper-lockfile/pull/151
> add AWS CodeBuild

- README.md
- example-circleci-workflows.md
> docs(README): fix example circleci workflows config

- lib/git-helpers.js
- test/__snapshots__/update.js.snap
- test/update.js
supersedes https://github.com/greenkeeperio/greenkeeper-lockfile/pull/188
> fix: amend comments, for reals now

- ci-services/tests.js
> APPVEYOR - True (true on Ubuntu image) if build runs in AppVeyor environment
https://www.appveyor.com/docs/environment-variables/
> fix: appveyor test
